// <auto-generated />
using System;
using HealthPlus.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthPlus.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606021921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthPlus.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Entity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.HealthMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal?>("BloodSugar")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<Guid>("HealthRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("MeasuredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("MeasuredAt")
                        .IsDescending();

                    b.ToTable("HealthMetrics", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Allergies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthRecords", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.MedicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("MedicalHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("MedicalHistoryId");

                    b.ToTable("MedicalDocuments", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.MedicalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HealthRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hospital")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitDate")
                        .IsDescending();

                    b.ToTable("MedicalHistory", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "read",
                            Name = "users.read",
                            Resource = "users"
                        },
                        new
                        {
                            Id = 2,
                            Action = "write",
                            Name = "users.write",
                            Resource = "users"
                        },
                        new
                        {
                            Id = 3,
                            Action = "delete",
                            Name = "users.delete",
                            Resource = "users"
                        },
                        new
                        {
                            Id = 4,
                            Action = "read",
                            Name = "health_records.read",
                            Resource = "health_records"
                        },
                        new
                        {
                            Id = 5,
                            Action = "write",
                            Name = "health_records.write",
                            Resource = "health_records"
                        },
                        new
                        {
                            Id = 6,
                            Action = "read",
                            Name = "vaccines.read",
                            Resource = "vaccines"
                        },
                        new
                        {
                            Id = 7,
                            Action = "write",
                            Name = "vaccines.write",
                            Resource = "vaccines"
                        },
                        new
                        {
                            Id = 8,
                            Action = "read",
                            Name = "audit_logs.read",
                            Resource = "audit_logs"
                        },
                        new
                        {
                            Id = 9,
                            Action = "manage",
                            Name = "system.manage",
                            Resource = "system"
                        });
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ImageStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("MedicalHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OcrConfidenceScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("OcrRawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MedicalHistoryId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("FrequencyPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timing")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Push");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RepeatType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("RepeatUntil")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsSent");

                    b.HasIndex("RemindAt");

                    b.HasIndex("ReminderType");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.ReminderLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMsg")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("ReminderLogs", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5457),
                            Description = "Quản trị viên hệ thống",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5461),
                            Description = "Bác sĩ/nhân viên y tế",
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5463),
                            Description = "Người dùng thông thường",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        });
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tên ứng dụng",
                            SettingKey = "app.name",
                            SettingValue = "Health+",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5824)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phiên bản hiện tại",
                            SettingKey = "app.version",
                            SettingValue = "1.0.0",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5828)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thời hạn access token (phút)",
                            SettingKey = "jwt.access_token_expiry",
                            SettingValue = "15",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5831)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thời hạn refresh token (ngày)",
                            SettingKey = "jwt.refresh_token_expiry",
                            SettingValue = "7",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5832)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nhà cung cấp OCR",
                            SettingKey = "ocr.provider",
                            SettingValue = "tesseract",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5833)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Nhà cung cấp storage",
                            SettingKey = "storage.provider",
                            SettingValue = "local",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5834)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Số ngày nhắc trước lịch tiêm/tái khám",
                            SettingKey = "reminder.advance_days",
                            SettingValue = "3",
                            UpdatedAt = new DateTime(2026, 6, 6, 2, 19, 19, 737, DateTimeKind.Utc).AddTicks(5836)
                        });
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.UserNotificationSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("FollowUpReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MedicineReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("QuietHourEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("QuietHourStart")
                        .HasColumnType("time");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("VaccineReminderEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("UserNotificationSettings", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AdministeredBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("HealthRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("InjectionDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SideEffects")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Completed");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Vaccines", (string)null);
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.VaccineScheduleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecommendedAge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("VaccineScheduleTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoseNumber = 1,
                            Notes = "Tiêm trong 24 giờ đầu",
                            RecommendedAge = "Sơ sinh",
                            VaccineName = "BCG (Lao)"
                        },
                        new
                        {
                            Id = 2,
                            DoseNumber = 1,
                            Notes = "Tiêm trong 24 giờ đầu",
                            RecommendedAge = "Sơ sinh",
                            VaccineName = "Viêm gan B"
                        },
                        new
                        {
                            Id = 3,
                            DoseNumber = 2,
                            IntervalDays = 60,
                            RecommendedAge = "2 tháng",
                            VaccineName = "Viêm gan B"
                        },
                        new
                        {
                            Id = 4,
                            DoseNumber = 3,
                            IntervalDays = 60,
                            RecommendedAge = "4 tháng",
                            VaccineName = "Viêm gan B"
                        },
                        new
                        {
                            Id = 5,
                            DoseNumber = 1,
                            RecommendedAge = "2 tháng",
                            VaccineName = "Bạch hầu-Ho gà-Uốn ván (DTP)"
                        },
                        new
                        {
                            Id = 6,
                            DoseNumber = 2,
                            IntervalDays = 30,
                            RecommendedAge = "3 tháng",
                            VaccineName = "Bạch hầu-Ho gà-Uốn ván (DTP)"
                        },
                        new
                        {
                            Id = 7,
                            DoseNumber = 3,
                            IntervalDays = 30,
                            RecommendedAge = "4 tháng",
                            VaccineName = "Bạch hầu-Ho gà-Uốn ván (DTP)"
                        },
                        new
                        {
                            Id = 8,
                            DoseNumber = 1,
                            RecommendedAge = "2 tháng",
                            VaccineName = "Bại liệt (OPV)"
                        },
                        new
                        {
                            Id = 9,
                            DoseNumber = 2,
                            IntervalDays = 30,
                            RecommendedAge = "3 tháng",
                            VaccineName = "Bại liệt (OPV)"
                        },
                        new
                        {
                            Id = 10,
                            DoseNumber = 3,
                            IntervalDays = 30,
                            RecommendedAge = "4 tháng",
                            VaccineName = "Bại liệt (OPV)"
                        },
                        new
                        {
                            Id = 11,
                            DoseNumber = 1,
                            RecommendedAge = "9 tháng",
                            VaccineName = "Sởi"
                        },
                        new
                        {
                            Id = 12,
                            DoseNumber = 1,
                            IntervalDays = 90,
                            RecommendedAge = "12 tháng",
                            VaccineName = "Sởi-Quai bị-Rubella"
                        },
                        new
                        {
                            Id = 13,
                            DoseNumber = 1,
                            RecommendedAge = "12 tháng",
                            VaccineName = "Viêm não Nhật Bản B"
                        },
                        new
                        {
                            Id = 14,
                            DoseNumber = 2,
                            IntervalDays = 14,
                            Notes = "14 ngày sau mũi 1",
                            RecommendedAge = "12 tháng",
                            VaccineName = "Viêm não Nhật Bản B"
                        },
                        new
                        {
                            Id = 15,
                            DoseNumber = 3,
                            IntervalDays = 365,
                            Notes = "1 năm sau mũi 2",
                            RecommendedAge = "24 tháng",
                            VaccineName = "Viêm não Nhật Bản B"
                        },
                        new
                        {
                            Id = 16,
                            DoseNumber = 1,
                            RecommendedAge = "12 tuổi trở lên",
                            VaccineName = "COVID-19"
                        },
                        new
                        {
                            Id = 17,
                            DoseNumber = 2,
                            IntervalDays = 28,
                            RecommendedAge = "12 tuổi trở lên",
                            VaccineName = "COVID-19"
                        },
                        new
                        {
                            Id = 18,
                            DoseNumber = 1,
                            Notes = "Nhắc lại mỗi năm",
                            RecommendedAge = "Hàng năm",
                            VaccineName = "Cúm"
                        });
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.HealthMetric", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("HealthMetrics")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.MedicalDocument", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.MedicalHistory", "MedicalHistory")
                        .WithMany("Documents")
                        .HasForeignKey("MedicalHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.MedicalHistory", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.MedicalHistory", "MedicalHistory")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MedicalHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.ReminderLog", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.Reminder", "Reminder")
                        .WithMany("Logs")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPlus.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.UserNotificationSetting", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithOne("NotificationSetting")
                        .HasForeignKey("HealthPlus.Domain.Entities.UserNotificationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Vaccine", b =>
                {
                    b.HasOne("HealthPlus.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("Vaccines")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPlus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.HealthRecord", b =>
                {
                    b.Navigation("HealthMetrics");

                    b.Navigation("MedicalHistories");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.MedicalHistory", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Reminder", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HealthPlus.Domain.Entities.User", b =>
                {
                    b.Navigation("HealthRecords");

                    b.Navigation("NotificationSetting");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
